// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/hare.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// top message of the protocol
type HareMessage struct {
	PubKey               []byte        `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	InnerSig             []byte        `protobuf:"bytes,2,opt,name=innerSig,proto3" json:"innerSig,omitempty"`
	Message              *InnerMessage `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Cert                 *Certificate  `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HareMessage) Reset()         { *m = HareMessage{} }
func (m *HareMessage) String() string { return proto.CompactTextString(m) }
func (*HareMessage) ProtoMessage()    {}
func (*HareMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_03c7555ad582658b, []int{0}
}

func (m *HareMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HareMessage.Unmarshal(m, b)
}
func (m *HareMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HareMessage.Marshal(b, m, deterministic)
}
func (m *HareMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HareMessage.Merge(m, src)
}
func (m *HareMessage) XXX_Size() int {
	return xxx_messageInfo_HareMessage.Size(m)
}
func (m *HareMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HareMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HareMessage proto.InternalMessageInfo

func (m *HareMessage) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *HareMessage) GetInnerSig() []byte {
	if m != nil {
		return m.InnerSig
	}
	return nil
}

func (m *HareMessage) GetMessage() *InnerMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *HareMessage) GetCert() *Certificate {
	if m != nil {
		return m.Cert
	}
	return nil
}

// the certificate
type Certificate struct {
	Blocks               [][]byte            `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	AggMsgs              *AggregatedMessages `protobuf:"bytes,2,opt,name=aggMsgs,proto3" json:"aggMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_03c7555ad582658b, []int{1}
}

func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetBlocks() [][]byte {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Certificate) GetAggMsgs() *AggregatedMessages {
	if m != nil {
		return m.AggMsgs
	}
	return nil
}

// Aggregated messages
type AggregatedMessages struct {
	Messages             []*HareMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	AggSig               []byte         `protobuf:"bytes,2,opt,name=aggSig,proto3" json:"aggSig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AggregatedMessages) Reset()         { *m = AggregatedMessages{} }
func (m *AggregatedMessages) String() string { return proto.CompactTextString(m) }
func (*AggregatedMessages) ProtoMessage()    {}
func (*AggregatedMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_03c7555ad582658b, []int{2}
}

func (m *AggregatedMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatedMessages.Unmarshal(m, b)
}
func (m *AggregatedMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatedMessages.Marshal(b, m, deterministic)
}
func (m *AggregatedMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatedMessages.Merge(m, src)
}
func (m *AggregatedMessages) XXX_Size() int {
	return xxx_messageInfo_AggregatedMessages.Size(m)
}
func (m *AggregatedMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatedMessages.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatedMessages proto.InternalMessageInfo

func (m *AggregatedMessages) GetMessages() []*HareMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *AggregatedMessages) GetAggSig() []byte {
	if m != nil {
		return m.AggSig
	}
	return nil
}

// basic message
type InnerMessage struct {
	Type                 int32               `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Layer                []byte              `protobuf:"bytes,2,opt,name=layer,proto3" json:"layer,omitempty"`
	K                    uint32              `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	Ki                   uint32              `protobuf:"varint,4,opt,name=ki,proto3" json:"ki,omitempty"`
	Blocks               [][]byte            `protobuf:"bytes,5,rep,name=blocks,proto3" json:"blocks,omitempty"`
	RoleProof            []byte              `protobuf:"bytes,6,opt,name=roleProof,proto3" json:"roleProof,omitempty"`
	Svp                  *AggregatedMessages `protobuf:"bytes,7,opt,name=svp,proto3" json:"svp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InnerMessage) Reset()         { *m = InnerMessage{} }
func (m *InnerMessage) String() string { return proto.CompactTextString(m) }
func (*InnerMessage) ProtoMessage()    {}
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_03c7555ad582658b, []int{3}
}

func (m *InnerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMessage.Unmarshal(m, b)
}
func (m *InnerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMessage.Marshal(b, m, deterministic)
}
func (m *InnerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMessage.Merge(m, src)
}
func (m *InnerMessage) XXX_Size() int {
	return xxx_messageInfo_InnerMessage.Size(m)
}
func (m *InnerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMessage proto.InternalMessageInfo

func (m *InnerMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *InnerMessage) GetLayer() []byte {
	if m != nil {
		return m.Layer
	}
	return nil
}

func (m *InnerMessage) GetK() uint32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *InnerMessage) GetKi() uint32 {
	if m != nil {
		return m.Ki
	}
	return 0
}

func (m *InnerMessage) GetBlocks() [][]byte {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *InnerMessage) GetRoleProof() []byte {
	if m != nil {
		return m.RoleProof
	}
	return nil
}

func (m *InnerMessage) GetSvp() *AggregatedMessages {
	if m != nil {
		return m.Svp
	}
	return nil
}

func init() {
	proto.RegisterType((*HareMessage)(nil), "pb.HareMessage")
	proto.RegisterType((*Certificate)(nil), "pb.Certificate")
	proto.RegisterType((*AggregatedMessages)(nil), "pb.AggregatedMessages")
	proto.RegisterType((*InnerMessage)(nil), "pb.InnerMessage")
}

func init() { proto.RegisterFile("pb/hare.proto", fileDescriptor_03c7555ad582658b) }

var fileDescriptor_03c7555ad582658b = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xdd, 0x4a, 0x33, 0x31,
	0x10, 0x25, 0xdb, 0xed, 0xcf, 0x37, 0xdb, 0x7e, 0xca, 0x20, 0x65, 0x11, 0x2f, 0xca, 0x7a, 0x53,
	0x14, 0xaa, 0xd4, 0x27, 0x50, 0x6f, 0x14, 0x29, 0x48, 0xbc, 0x10, 0xbd, 0x4b, 0xea, 0x34, 0x2e,
	0x5b, 0xbb, 0x21, 0x59, 0x85, 0xbe, 0x86, 0x0f, 0xe3, 0xf3, 0x49, 0xb2, 0x69, 0xbb, 0x22, 0x78,
	0x97, 0x33, 0xe7, 0xcc, 0xcc, 0x99, 0x43, 0x60, 0xa0, 0xe5, 0xd9, 0xab, 0x30, 0x34, 0xd1, 0xa6,
	0xac, 0x4a, 0x8c, 0xb4, 0xcc, 0x3e, 0x19, 0x24, 0x37, 0xc2, 0xd0, 0x8c, 0xac, 0x15, 0x8a, 0x70,
	0x08, 0x1d, 0xfd, 0x2e, 0xef, 0x68, 0x9d, 0xb2, 0x11, 0x1b, 0xf7, 0x79, 0x40, 0x78, 0x08, 0xbd,
	0x7c, 0xb5, 0x22, 0xf3, 0x90, 0xab, 0x34, 0xf2, 0xcc, 0x16, 0xe3, 0x09, 0x74, 0xdf, 0xea, 0xf6,
	0xb4, 0x35, 0x62, 0xe3, 0x64, 0xba, 0x3f, 0xd1, 0x72, 0x72, 0xeb, 0xe8, 0x30, 0x96, 0x6f, 0x04,
	0x78, 0x0c, 0xf1, 0x9c, 0x4c, 0x95, 0xc6, 0x5e, 0xb8, 0xe7, 0x84, 0xd7, 0x64, 0xaa, 0x7c, 0x91,
	0xcf, 0x45, 0x45, 0xdc, 0x93, 0xd9, 0x23, 0x24, 0x8d, 0xa2, 0xf3, 0x24, 0x97, 0xe5, 0xbc, 0xb0,
	0x29, 0x1b, 0xb5, 0x9c, 0xa7, 0x1a, 0xe1, 0x39, 0x74, 0x85, 0x52, 0x33, 0xab, 0xac, 0xb7, 0x94,
	0x4c, 0x87, 0x6e, 0xdc, 0xa5, 0x52, 0x86, 0x94, 0xa8, 0xe8, 0x25, 0x2c, 0xb7, 0x7c, 0x23, 0xcb,
	0x9e, 0x00, 0x7f, 0xd3, 0x78, 0x0a, 0xbd, 0x60, 0xaf, 0xde, 0x10, 0x7c, 0x35, 0x62, 0xe1, 0x5b,
	0x81, 0x33, 0x23, 0x94, 0xda, 0xc5, 0x10, 0x50, 0xf6, 0xc5, 0xa0, 0xdf, 0x3c, 0x19, 0x11, 0xe2,
	0x6a, 0xad, 0xc9, 0xe7, 0xd8, 0xe6, 0xfe, 0x8d, 0x07, 0xd0, 0x5e, 0x8a, 0x35, 0x99, 0xd0, 0x5b,
	0x03, 0xec, 0x03, 0x2b, 0x7c, 0x72, 0x03, 0xce, 0x0a, 0xfc, 0x0f, 0x51, 0x91, 0xfb, 0x7c, 0x06,
	0x3c, 0x2a, 0xf2, 0xc6, 0xf5, 0xed, 0x1f, 0xd7, 0x1f, 0xc1, 0x3f, 0x53, 0x2e, 0xe9, 0xde, 0x94,
	0xe5, 0x22, 0xed, 0xf8, 0x79, 0xbb, 0x02, 0x8e, 0xa1, 0x65, 0x3f, 0x74, 0xda, 0xfd, 0x33, 0x17,
	0x27, 0xb9, 0x8a, 0x9f, 0x23, 0x2d, 0x65, 0xc7, 0x7f, 0x89, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc3, 0xbc, 0xbf, 0x03, 0x23, 0x02, 0x00, 0x00,
}
